# Webscraping NBA Data

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
# Empty list to put in appended dataframes in
df_list = []
# List of years to input in the outermost for loop
years = ['2010-11', '2012-13', '2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19']
# List of months to input in the second for loop
months = ['October', 'November', 'December', 'January', 'February', 'March', 'April']
# List of column headers to input in the innermost for loop
columns = ['Starters','MP','FG','FGA','FG%','3P','3PA','3P%','FT','FTA','FT%','ORB','DRB','TRB','AST','STL','BLK','TOV','PF','PTS','+/-']

# Outermost for loop used to loop through every regular season except for the 2011-12 season because that year was shortened
for h in range(0, len(years)):
    # Code that allows you to click on the basketball reference website
    driver = webdriver.Chrome(executable_path='C:/Users/yesla/bin/chromedriver.exe')
    driver.get("https://www.basketball-reference.com/leagues/")
    # Code that finds the particular NBA season in this iteration
    driver.find_element_by_link_text(years[h]).click()
    # Clicks on the 'Schedule and Results' section of the page
    driver.find_element_by_link_text("Schedule and Results").click()
    for i in range(0, len(months)):
        # Get all of the box scores for October in the 2010-2011 season
        driver.find_element_by_link_text(months[i]).click()
        allgames = driver.find_element_by_id("schedule")
        tr_list = allgames.find_elements_by_tag_name('tr')
    
        # First for loop to get the first 30 boxscores
        if months[i] != 'April':
            for j in range(1,len(tr_list)):
            # Use try statement to get passed the weird table formatting
                try:
                    # Click on the boxscores for the NBA games
                    allgames = driver.find_element_by_id("schedule")
                    tr_list = allgames.find_elements_by_tag_name('tr')
                    tr_list[j].find_element_by_link_text("Box Score").click()
    
                    # Get team names for later use
                    soup = BeautifulSoup(driver.page_source, 'html.parser')
                    table = soup.find(name='table', attrs={'id':'line_score'})
                    html_str = str(table)
                    df = pd.read_html(html_str)[0]
                    team1 = df['Unnamed: 0'][1]
                    team2 = df['Unnamed: 0'][2]
    
                    # Extract and transform first teams boxscore
                    table1 = soup.find(name='table', attrs={'id':'box-'+team1+'-game-basic'})
                    html_str1 = str(table1)
                    df1 = pd.read_html(html_str1)[0]
                    df1 = pd.DataFrame(df1.to_records())
                    first_column = df1.columns[0]
                    df1 = df1.drop([first_column], axis=1)
                    df1.columns = columns
                    df1 = df1[(df1['Starters'] != 'Reserves') & (df1['Starters'] != 'Team Totals') & (df1['MP'] != 'Did Not Play')]
    
                    # Extract and transform second teams boxscore
                    table2 = soup.find(name='table', attrs={'id':'box-'+team2+'-game-basic'})
                    html_str2 = str(table2)
                    df2 = pd.read_html(html_str2)[0]
                    df2 = pd.DataFrame(df2.to_records())
                    first_column = df2.columns[0]
                    df2 = df2.drop([first_column], axis=1)
                    df2.columns = columns
                    df2 = df2[(df2['Starters'] != 'Reserves') & (df2['Starters'] != 'Team Totals') & (df2['MP'] != 'Did Not Play')]
    
                    # Concatenate both boxscores then append to empty list
                    df_comp = pd.concat([df1,df2])
                    df_list.append(df_comp)
                    driver.back()
                except:
                    pass
        else:
            for j in range(60,len(tr_list)):
            # Use try statement to get passed the weird table formatting
                try:
                    # Click on the boxscores for the NBA games
                    allgames = driver.find_element_by_id("schedule")
                    tr_list = allgames.find_elements_by_tag_name('tr')
                    tr_list[j].find_element_by_link_text("Box Score").click()
    
                    # Get team names for later use
                    soup = BeautifulSoup(driver.page_source, 'html.parser')
                    table = soup.find(name='table', attrs={'id':'line_score'})
                    html_str = str(table)
                    df = pd.read_html(html_str)[0]
                    team1 = df['Unnamed: 0'][1]
                    team2 = df['Unnamed: 0'][2]
    
                    # Extract and transform first teams boxscore
                    table1 = soup.find(name='table', attrs={'id':'box-'+team1+'-game-basic'})
                    html_str1 = str(table1)
                    df1 = pd.read_html(html_str1)[0]
                    df1 = pd.DataFrame(df1.to_records())
                    first_column = df1.columns[0]
                    df1 = df1.drop([first_column], axis=1)
                    df1.columns = columns
                    df1 = df1[(df1['Starters'] != 'Reserves') & (df1['Starters'] != 'Team Totals') & (df1['MP'] != 'Did Not Play')]
    
                    # Extract and transform second teams boxscore
                    table2 = soup.find(name='table', attrs={'id':'box-'+team2+'-game-basic'})
                    html_str2 = str(table2)
                    df2 = pd.read_html(html_str2)[0]
                    df2 = pd.DataFrame(df2.to_records())
                    first_column = df2.columns[0]
                    df2 = df2.drop([first_column], axis=1)
                    df2.columns = columns
                    df2 = df2[(df2['Starters'] != 'Reserves') & (df2['Starters'] != 'Team Totals') & (df2['MP'] != 'Did Not Play')]
    
                    # Concatenate both boxscores then append to empty list
                    df_comp = pd.concat([df1,df2])
                    df_list.append(df_comp)
                    driver.back()
                except:
                    break

# 2011-2012 NBA Regular Season Data

In [31]:
# Code opens the basketball reference website and clicks on the schedule and results section of the 2011-2012 season
driver = webdriver.Chrome(executable_path='C:/Users/yesla/bin/chromedriver.exe')
driver.implicitly_wait(1)
driver.get("https://www.basketball-reference.com/leagues/")
driver.find_element_by_link_text('2011-12').click()
driver.find_element_by_link_text("Schedule and Results").click()

df_list2 = []
months2 = ['december', 'january', 'february', 'march', 'april']
columns = ['Starters','MP','FG','FGA','FG%','3P','3PA','3P%','FT','FTA','FT%','ORB','DRB','TRB','AST','STL','BLK','TOV','PF','PTS','+/-']

for i in range(0, len(months2)):
    # Get all of the box scores for October in the 2010-2011 season
    driver.get('https://www.basketball-reference.com/leagues/NBA_2012_games-'+months2[i]+'.html')
    allgames = driver.find_element_by_id("schedule")
    tr_list = allgames.find_elements_by_tag_name('tr')
    
    # First for loop to get the first 30 boxscores
    if months2[i] != 'april':
        for j in range(1,len(tr_list)):
        # Use try statement to get passed the weird table formatting
            try:
                # Click on the boxscores for the NBA games
                allgames = driver.find_element_by_id("schedule")
                tr_list = allgames.find_elements_by_tag_name('tr')
                tr_list[j].find_element_by_link_text("Box Score").click()
    
                # Get team names for later use
                soup = BeautifulSoup(driver.page_source, 'html.parser')
                table = soup.find(name='table', attrs={'id':'line_score'})
                html_str = str(table)
                df = pd.read_html(html_str)[0]
                team1 = df['Unnamed: 0'][1]
                team2 = df['Unnamed: 0'][2]
    
                # Extract and transform first teams boxscore
                table1 = soup.find(name='table', attrs={'id':'box-'+team1+'-game-basic'})
                html_str1 = str(table1)
                df1 = pd.read_html(html_str1)[0]
                df1 = pd.DataFrame(df1.to_records())
                first_column = df1.columns[0]
                df1 = df1.drop([first_column], axis=1)
                df1.columns = columns
                df1 = df1[(df1['Starters'] != 'Reserves') & (df1['Starters'] != 'Team Totals') & (df1['MP'] != 'Did Not Play')]
    
                # Extract and transform second teams boxscore
                table2 = soup.find(name='table', attrs={'id':'box-'+team2+'-game-basic'})
                html_str2 = str(table2)
                df2 = pd.read_html(html_str2)[0]
                df2 = pd.DataFrame(df2.to_records())
                first_column = df2.columns[0]
                df2 = df2.drop([first_column], axis=1)
                df2.columns = columns
                df2 = df2[(df2['Starters'] != 'Reserves') & (df2['Starters'] != 'Team Totals') & (df2['MP'] != 'Did Not Play')]
    
                # Concatenate both boxscores then append to empty list
                df_comp = pd.concat([df1,df2])
                df_list2.append(df_comp)
                driver.back()
            except:
                pass
    else:
        for j in range(1,len(tr_list)):
        # Use try statement to get passed the weird table formatting
            try:
                # Click on the boxscores for the NBA games
                allgames = driver.find_element_by_id("schedule")
                tr_list = allgames.find_elements_by_tag_name('tr')
                tr_list[j].find_element_by_link_text("Box Score").click()
    
                # Get team names for later use
                soup = BeautifulSoup(driver.page_source, 'html.parser')
                table = soup.find(name='table', attrs={'id':'line_score'})
                html_str = str(table)
                df = pd.read_html(html_str)[0]
                team1 = df['Unnamed: 0'][1]
                team2 = df['Unnamed: 0'][2]
    
                # Extract and transform first teams boxscore
                table1 = soup.find(name='table', attrs={'id':'box-'+team1+'-game-basic'})
                html_str1 = str(table1)
                df1 = pd.read_html(html_str1)[0]
                df1 = pd.DataFrame(df1.to_records())
                first_column = df1.columns[0]
                df1 = df1.drop([first_column], axis=1)
                df1.columns = columns
                df1 = df1[(df1['Starters'] != 'Reserves') & (df1['Starters'] != 'Team Totals') & (df1['MP'] != 'Did Not Play')]
    
                # Extract and transform second teams boxscore
                table2 = soup.find(name='table', attrs={'id':'box-'+team2+'-game-basic'})
                html_str2 = str(table2)
                df2 = pd.read_html(html_str2)[0]
                df2 = pd.DataFrame(df2.to_records())
                first_column = df2.columns[0]
                df2 = df2.drop([first_column], axis=1)
                df2.columns = columns
                df2 = df2[(df2['Starters'] != 'Reserves') & (df2['Starters'] != 'Team Totals') & (df2['MP'] != 'Did Not Play')]
    
                # Concatenate both boxscores then append to empty list
                df_comp = pd.concat([df1,df2])
                df_list2.append(df_comp)
                driver.back()
            except:
                break

In [32]:
# Concatenates all of the extracted box score df's and then exports the concatenated df into a csv file for the next part
df_full = pd.concat(df_list2)
df_full.to_csv(r'C:\Users\yesla\OneDrive\Documents\GitHub\predicting-nba-games\df-2011-12.csv', index = False)
df_full

,Starters,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
0,Rajon Rondo,41:16,11,19,.579,0,1,.000,9,12,...,1,4,5,13,5,0,5,2,31,+3
1,Ray Allen,37:42,7,12,.583,2,3,.667,4,4,...,3,1,4,3,0,0,4,1,20,+6
2,Kevin Garnett,37:03,6,13,.462,0,0,NaN,3,6,...,1,7,8,3,0,1,3,5,15,-4
3,Jermaine O'Neal,17:11,2,5,.400,0,0,NaN,2,3,...,0,2,2,0,0,2,1,5,6,+5
4,Sasha Pavlović,15:07,0,0,NaN,0,0,NaN,0,0,...,0,1,1,1,0,0,0,4,0,-4
6,Marquis Daniels,29:48,2,8,.250,0,1,.000,0,0,...,1,5,6,5,1,1,0,5,4,-2
7,Brandon Bass,27:36,9,13,.692,0,0,NaN,2,2,...,5,6,11,0,1,0,1,3,20,-1
8,Chris Wilcox,14:03,2,3,.667,0,0,NaN,0,0,...,2,1,3,0,0,1,1,1,4,-4
9,Keyon Dooling,11:23,0,1,.000,0,0,NaN,4,4,...,0,1,1,3,0,0,2,2,4,-4
10,Avery Bradley,8:49,0,2,.000,0,0,NaN,0,0,...,0,0,0,0,0,0,1,0,0,-5
11,E'Twaun Moore,0:04,0,0,NaN,0,0,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
0,Tyson Chandler,36:48,1,2,.500,0,0,NaN,5,8,...,2,1,3,2,0,6,0,2,7,-5
1,Toney Douglas,35:04,8,19,.421,2,6,.333,1,2,...,0,2,2,4,3,0,2,4,19,+12
2,Amar'e Stoudemire,34:42,8,11,.727,2,2,1.000,3,4,...,0,6,6,2,2,2,1,2,21,-3
3,Landry Fields,33:52,3,7,.429,1,3,.333,0,0,...,1,1,2,3,2,0,2,3,7,-11
4,Carmelo Anthony,33:35,10,17,.588,4,7,.571,13,15,...,1,7,8,3,2,1,5,4,37,+15
6,Iman Shumpert,22:02,3,13,.231,0,1,.000,5,5,...,1,3,4,1,0,0,2,2,11,-10
7,Henry Walker,14:43,0,1,.000,0,1,.000,0,0,...,0,0,0,0,0,0,3,4,0,-5
8,Jared Jeffries,12:30,1,3,.333,0,0,NaN,0,0,...,1,0,1,0,0,1,0,2,2,+3
9,Josh Harrellson,9:03,0,0,NaN,0,0,NaN,0,0,...,0,2,2,1,0,1,1,0,0,+9
10,Renaldo Balkman,7:41,1,1,1.000,0,0,NaN,0,0,...,2,1,3,1,0,0,0,2,2,+5
0,LeBron James,36:16,11,19,.579,0,0,NaN,15,19,...,3,7,10,6,2,2,3,3,37,+27
1,Dwyane Wade,34:39,11,21,.524,0,0,NaN,4,6,...,1,7,8,6,1,1,5,4,26,+10
2,Joel Anthony,25:38,2,3,.667,0,0,NaN,2,3,...,1,1,2,0,0,1,0,1,6,+23
3,Mario Chalmers,24:21,1,1,1.000,0,0,NaN,1,1,...,0,1,1,4,4,0,2,3,3,+25
4,Chris Bosh,23:59,2,9,.222,0,0,NaN,0,0,...,1,6,7,1,1,1,2,5,4,+16
6,Udonis Haslem,32:16,3,6,.500,0,0,NaN,3,5,...,6,8,14,1,0,1,3,5,9,-4
7,Norris Cole,23:39,3,8,.375,1,1,1.000,0,1,...,0,2,2,0,1,0,4,3,7,-14
8,James Jones,18:26,3,6,.500,3,5,.600,0,1,...,0,2,2,0,0,0,2,2,9,-15
9,Juwan Howard,7:55,2,3,.667,0,0,NaN,0,0,...,2,0,2,0,0,0,0,0,4,+2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,Charles Jenkins,26:00,8,13,.615,0,0,NaN,0,0,...,0,3,3,7,3,0,0,4,16,+1
6,Mikki Moore,29:02,1,4,.250,0,0,NaN,0,0,...,0,5,5,2,1,1,0,3,2,-3
7,Dominic McGuire,26:52,5,11,.455,0,0,NaN,1,1,...,0,3,3,8,2,0,6,1,11,-4
8,Andris Biedriņš,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,David Lee,Not With Team,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Josh McRoberts,37:43,6,12,.500,2,3,.667,2,2,...,2,7,9,4,0,0,2,3,16,-14
1,Jordan Hill,29:43,4,12,.333,0,0,NaN,0,0,...,2,6,8,2,3,1,2,4,8,-12
2,Devin Ebanks,28:46,7,11,.636,0,0,NaN,0,0,...,2,3,5,0,0,1,2,1,14,-20
3,Ramon Sessions,26:35,6,13,.462,0,1,.000,2,3,...,1,2,3,4,0,0,3,1,14,-20
4,Steve Blake,23:02,1,5,.200,1,2,.500,1,2,...,0,0,0,6,0,0,0,0,4,-14
6,Troy Murphy,28:34,6,10,.600,0,0,NaN,0,0,...,3,3,6,3,1,0,1,2,12,-8
7,Andrew Goudelock,24:58,4,12,.333,3,5,.600,0,0,...,0,5,5,2,0,0,2,1,11,-3
8,Darius Morris,21:25,4,10,.400,1,3,.333,0,0,...,0,3,3,5,0,0,2,2,9,+3
9,Christian Eyenga,19:14,3,6,.500,0,1,.000,2,2,...,1,1,2,1,0,1,1,0,8,+3
10,Metta World Peace,Player Suspended,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Pau Gasol,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Andrew Bynum,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Kobe Bryant,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,DeMarcus Cousins,37:47,9,19,.474,0,1,.000,5,7,...,8,11,19,2,1,0,1,5,23,+19
1,Jason Thompson,35:37,7,11,.636,0,0,NaN,3,4,...,3,7,10,3,2,2,0,0,17,+22
2,Tyreke Evans,31:12,9,14,.643,0,1,.000,3,4,...,1,3,4,2,1,0,4,0,21,+17
3,Travis Outlaw,28:03,4,10,.400,2,4,.500,1,2,...,1,1,2,0,0,2,1,0,11,+17
4,Isaiah Thomas,26:01,5,6,.833,1,1,1.000,0,0,...,0,1,1,7,0,0,1,2,11,+13
6,Jimmer Fredette,24:24,4,10,.400,2,4,.500,0,0,...,0,1,1,3,0,1,0,1,10,+2
7,Tyler Honeycutt,15:10,3,5,.600,1,1,1.000,0,0,...,1,4,5,2,0,0,0,0,7,-4
8,Donté Greene,12:23,2,7,.286,0,2,.000,1,1,...,0,0,0,0,0,0,0,0,5,-5
9,Francisco García,12:00,1,4,.250,0,1,.000,0,0,...,0,5,5,1,0,1,0,2,2,+2
10,Terrence Williams,9:35,2,4,.500,0,0,NaN,0,0,...,0,1,1,1,1,1,0,0,4,+2
11,Chuck Hayes,7:48,1,2,.500,0,0,NaN,0,0,...,0,0,0,0,1,0,1,0,2,0
12,Hassan Whiteside,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Code used when developing final code

In [ ]:
df_full = pd.concat(df_list,df_list2)
df_full

In [12]:
team1

'BOS'

In [13]:
# Extract and transform first teams boxscore
table1 = soup.find(name='table', attrs={'id':'box-'+team1+'-game-basic'})
html_str1 = str(table1)
df1 = pd.read_html(html_str1)[0]
df1 = pd.DataFrame(df1.to_records())
first_column = df1.columns[0]
df1 = df1.drop([first_column], axis=1)
df1.columns = columns
df1 = df1[(df1['Starters'] != 'Reserves') & (df1['Starters'] != 'Team Totals') & (df1['MP'] != 'Did Not Play')]
    
# Extract and transform second teams boxscore
table2 = soup.find(name='table', attrs={'id':'box-'+team2+'-game-basic'})
html_str2 = str(table2)
df2 = pd.read_html(html_str2)[0]
df2 = pd.DataFrame(df2.to_records())
first_column = df2.columns[0]
df2 = df2.drop([first_column], axis=1)
df2.columns = columns
df2 = df2[(df2['Starters'] != 'Reserves') & (df2['Starters'] != 'Team Totals') & (df2['MP'] != 'Did Not Play')]

NameError: name 'columns' is not defined

In [111]:
driver.find_element_by_link_text('October').click()

In [107]:
allgames = driver.find_element_by_id("schedule")
tr_list = allgames.find_elements_by_tag_name('tr')
tr_list[44].find_element_by_link_text("Box Score").click()
driver.back()

In [105]:
allgames = driver.find_element_by_id("schedule")
tr_list = allgames.find_elements_by_tag_name('tr')
len(tr_list)

45

In [103]:
for i in range(29,33):
    # Click on the boxscores for the NBA games
    try:
        allgames = driver.find_element_by_id("schedule")
        tr_list = allgames.find_elements_by_tag_name('tr')
        tr_list[i].find_element_by_link_text("Box Score").click()
        driver.back()
    except:
        pass

In [55]:
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [56]:
table = soup.find(name='table', attrs={'id':'line_score'})
html_str = str(table)
df = pd.read_html(html_str)[0]
team1 = df['Unnamed: 0'][1]
team2 = df['Unnamed: 0'][2]

In [57]:
columns = ['Starters','MP','FG','FGA','FG%','3P','3PA','3P%','FT','FTA','FT%','ORB','DRB','TRB','AST','STL','BLK','TOV','PF','PTS','+/-']

In [58]:
table1 = soup.find(name='table', attrs={'id':'box-'+team1+'-game-basic'})
html_str1 = str(table1)
df1 = pd.read_html(html_str1)[0]
df1

,Unnamed: 0_level_0,Basic Box Score Stats,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0,...,Unnamed: 11_level_0,Unnamed: 12_level_0,Unnamed: 13_level_0,Unnamed: 14_level_0,Unnamed: 15_level_0,Unnamed: 16_level_0,Unnamed: 17_level_0,Unnamed: 18_level_0,Unnamed: 19_level_0,Unnamed: 20_level_0
,Starters,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
0,LeBron James,42:39,10,21,.476,3,6,.500,8,12,...,0,4,4,3,1,2,8,1,31,+1
1,Chris Bosh,37:37,3,11,.273,0,0,NaN,2,2,...,2,6,8,2,1,1,1,4,8,-17
2,Dwyane Wade,36:41,4,16,.250,1,3,.333,4,6,...,0,4,4,6,3,0,6,4,13,-18
3,Joel Anthony,16:41,1,1,1.000,0,0,NaN,0,0,...,3,4,7,1,0,1,0,2,2,-12
4,Carlos Arroyo,12:33,1,3,.333,0,0,NaN,1,1,...,0,0,0,0,0,0,0,0,3,-5
5,Reserves,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
6,Udonis Haslem,30:36,3,7,.429,0,0,NaN,2,2,...,4,7,11,0,0,1,0,4,8,-4
7,Eddie House,26:30,3,8,.375,2,4,.500,0,0,...,0,0,0,2,1,0,0,0,8,0
8,James Jones,26:04,2,7,.286,2,7,.286,0,0,...,0,2,2,1,1,0,0,2,6,-2
9,Zydrunas Ilgauskas,10:39,0,0,NaN,0,0,NaN,1,2,...,2,1,3,0,3,1,2,4,1,+17
10,Jamaal Magloire,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Juwan Howard,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Mario Chalmers,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Team Totals,240,27,74,.365,8,20,.400,18,25,...,11,28,39,15,10,6,17,21,80,NaN

In [59]:
df1 = pd.DataFrame(df1.to_records())

In [60]:
first_column = df1.columns[0]
df1 = df1.drop([first_column], axis=1)
df1

,"('Unnamed: 0_level_0', 'Starters')","('Basic Box Score Stats', 'MP')","('Unnamed: 2_level_0', 'FG')","('Unnamed: 3_level_0', 'FGA')","('Unnamed: 4_level_0', 'FG%')","('Unnamed: 5_level_0', '3P')","('Unnamed: 6_level_0', '3PA')","('Unnamed: 7_level_0', '3P%')","('Unnamed: 8_level_0', 'FT')","('Unnamed: 9_level_0', 'FTA')",...,"('Unnamed: 11_level_0', 'ORB')","('Unnamed: 12_level_0', 'DRB')","('Unnamed: 13_level_0', 'TRB')","('Unnamed: 14_level_0', 'AST')","('Unnamed: 15_level_0', 'STL')","('Unnamed: 16_level_0', 'BLK')","('Unnamed: 17_level_0', 'TOV')","('Unnamed: 18_level_0', 'PF')","('Unnamed: 19_level_0', 'PTS')","('Unnamed: 20_level_0', '+/-')"
0,LeBron James,42:39,10,21,.476,3,6,.500,8,12,...,0,4,4,3,1,2,8,1,31,+1
1,Chris Bosh,37:37,3,11,.273,0,0,NaN,2,2,...,2,6,8,2,1,1,1,4,8,-17
2,Dwyane Wade,36:41,4,16,.250,1,3,.333,4,6,...,0,4,4,6,3,0,6,4,13,-18
3,Joel Anthony,16:41,1,1,1.000,0,0,NaN,0,0,...,3,4,7,1,0,1,0,2,2,-12
4,Carlos Arroyo,12:33,1,3,.333,0,0,NaN,1,1,...,0,0,0,0,0,0,0,0,3,-5
5,Reserves,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
6,Udonis Haslem,30:36,3,7,.429,0,0,NaN,2,2,...,4,7,11,0,0,1,0,4,8,-4
7,Eddie House,26:30,3,8,.375,2,4,.500,0,0,...,0,0,0,2,1,0,0,0,8,0
8,James Jones,26:04,2,7,.286,2,7,.286,0,0,...,0,2,2,1,1,0,0,2,6,-2
9,Zydrunas Ilgauskas,10:39,0,0,NaN,0,0,NaN,1,2,...,2,1,3,0,3,1,2,4,1,+17
10,Jamaal Magloire,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Juwan Howard,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Mario Chalmers,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Team Totals,240,27,74,.365,8,20,.400,18,25,...,11,28,39,15,10,6,17,21,80,NaN

In [61]:
df1.columns = columns
df1 = df1[(df1['Starters'] != 'Reserves') & (df1['Starters'] != 'Team Totals') & (df1['MP'] != 'Did Not Play')]

In [62]:
table2 = soup.find(name='table', attrs={'id':'box-'+team2+'-game-basic'})
html_str2 = str(table2)
df2 = pd.read_html(html_str2)[0]
df2 = pd.DataFrame(df2.to_records())
first_column = df2.columns[0]
df2 = df2.drop([first_column], axis=1)
df2.columns = columns
df2 = df2[(df2['Starters'] != 'Reserves') & (df2['Starters'] != 'Team Totals') & (df2['MP'] != 'Did Not Play')]

In [65]:
df2

,Starters,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
0,Rajon Rondo,41:29,2,9,.222,0,0,NaN,0,0,...,1,4,5,17,2,0,3,1,4,+4
1,Paul Pierce,40:33,4,7,.571,3,4,.750,8,8,...,1,8,9,3,1,0,3,3,19,+12
2,Ray Allen,39:16,7,13,.538,5,8,.625,1,1,...,0,1,1,1,0,0,1,1,20,-2
3,Kevin Garnett,35:13,4,11,.364,0,0,NaN,2,4,...,2,8,10,3,3,0,7,5,10,+7
4,Shaquille O'Neal,18:09,3,7,.429,0,0,NaN,3,8,...,2,5,7,0,0,1,1,2,9,+7
6,Glen Davis,29:24,6,7,.857,0,0,NaN,1,2,...,1,4,5,0,0,1,0,2,13,+1
7,Marquis Daniels,12:49,4,5,.800,0,1,.000,0,0,...,0,2,2,0,0,0,1,3,8,+3
8,Jermaine O'Neal,12:47,0,3,.000,0,0,NaN,1,2,...,1,1,2,0,0,2,1,1,1,+1
9,Nate Robinson,10:20,2,7,.286,0,3,.000,0,0,...,0,1,1,1,0,0,1,1,4,+7
10,Delonte West,Player Suspended,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
df_comp = pd.concat([df1,df2])
df_comp

,Starters,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
0,LeBron James,42:39,10,21,.476,3,6,.500,8,12,...,0,4,4,3,1,2,8,1,31,+1
1,Chris Bosh,37:37,3,11,.273,0,0,NaN,2,2,...,2,6,8,2,1,1,1,4,8,-17
2,Dwyane Wade,36:41,4,16,.250,1,3,.333,4,6,...,0,4,4,6,3,0,6,4,13,-18
3,Joel Anthony,16:41,1,1,1.000,0,0,NaN,0,0,...,3,4,7,1,0,1,0,2,2,-12
4,Carlos Arroyo,12:33,1,3,.333,0,0,NaN,1,1,...,0,0,0,0,0,0,0,0,3,-5
6,Udonis Haslem,30:36,3,7,.429,0,0,NaN,2,2,...,4,7,11,0,0,1,0,4,8,-4
7,Eddie House,26:30,3,8,.375,2,4,.500,0,0,...,0,0,0,2,1,0,0,0,8,0
8,James Jones,26:04,2,7,.286,2,7,.286,0,0,...,0,2,2,1,1,0,0,2,6,-2
9,Zydrunas Ilgauskas,10:39,0,0,NaN,0,0,NaN,1,2,...,2,1,3,0,3,1,2,4,1,+17
0,Rajon Rondo,41:29,2,9,.222,0,0,NaN,0,0,...,1,4,5,17,2,0,3,1,4,+4
1,Paul Pierce,40:33,4,7,.571,3,4,.750,8,8,...,1,8,9,3,1,0,3,3,19,+12
2,Ray Allen,39:16,7,13,.538,5,8,.625,1,1,...,0,1,1,1,0,0,1,1,20,-2
3,Kevin Garnett,35:13,4,11,.364,0,0,NaN,2,4,...,2,8,10,3,3,0,7,5,10,+7
4,Shaquille O'Neal,18:09,3,7,.429,0,0,NaN,3,8,...,2,5,7,0,0,1,1,2,9,+7
6,Glen Davis,29:24,6,7,.857,0,0,NaN,1,2,...,1,4,5,0,0,1,0,2,13,+1
7,Marquis Daniels,12:49,4,5,.800,0,1,.000,0,0,...,0,2,2,0,0,0,1,3,8,+3
8,Jermaine O'Neal,12:47,0,3,.000,0,0,NaN,1,2,...,1,1,2,0,0,2,1,1,1,+1
9,Nate Robinson,10:20,2,7,.286,0,3,.000,0,0,...,0,1,1,1,0,0,1,1,4,+7
10,Delonte West,Player Suspended,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN